ALTER TABLE `Users`
ADD
    `status` TINYINT NOT NULL DEFAULT 1,
ADD
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`,
ADD
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_at`,
ADD
    `deleted_at` TIMESTAMP NULL DEFAULT NULL AFTER `updated_at`;
